<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source/>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets/>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [SUN APR 12 21:26:28 CEST 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <Orders source="XSLTx">
      <xsl:for-each select="/table/T">
        <Order>
          <OrderNumber>
            <xsl:value-of select="O_ORDERKEY"/>
          </OrderNumber>
          <CustomerNumber>
            <xsl:value-of select="O_CUSTKEY"/>
          </CustomerNumber>
          <OrderStatus>
            <xsl:value-of select="O_ORDERSTATUS"/>
          </OrderStatus>
          <TotalPrice>
            <xsl:value-of select="O_TOTALPRICE"/>
          </TotalPrice>
          <OrderDate>
            <xsl:value-of select="O_ORDERDATE"/>
          </OrderDate>
          <OrderPriority>
            <xsl:value-of select="O_ORDER-PRIORITY"/>
          </OrderPriority>
          <Clerk>
            <xsl:value-of select="O_CLERK"/>
          </Clerk>
          <ShipPriority>
            <xsl:value-of select="O_SHIP-PRIORITY"/>
          </ShipPriority>
          <Comment>
            <xsl:value-of select="O_COMMENT"/>
          </Comment>
        </Order>
      </xsl:for-each>
    </Orders>
  </xsl:template>
</xsl:stylesheet>
 
